FROM python:3.11-slim
ARG DATA_DIRECTORY="demo-en_US"
ARG EXTRA_APT_INSTALL_PKGS=""

RUN apt update
RUN apt upgrade -y
RUN apt install -y $EXTRA_APT_INSTALL_PKGS

WORKDIR /console

COPY ./requirements.txt  ./
COPY ./console.py        ./
COPY ./package/          ./package/
COPY ./assets/           ./assets/
COPY ./$DATA_DIRECTORY/  ./data/
RUN ln -s ../assets      ./data/assets

RUN pip install --no-cache-dir -r requirements.txt -r data/requirements.txt

EXPOSE 8080

ENV PYTHONPATH=/console/package
WORKDIR /console/data/
CMD python3 /console/console.py console.ini

