FROM python:3.11-slim
ARG DATA_DIRECTORY="demo-en_US"
ARG EXTRA_APT_INSTALL_PKGS=""

RUN apt update
RUN apt upgrade -y
RUN apt install -y libusb-1.0-0 $EXTRA_APT_INSTALL_PKGS

WORKDIR /frontend

COPY ./requirements.txt  ./
COPY ./frontend.py       ./
COPY ./package/          ./package/
COPY ./resources/        ./resources/
COPY ./$DATA_DIRECTORY/  ./data/
RUN ln -s ../resources   ./data/resources

RUN pip install --no-cache-dir -r requirements.txt -r data/requirements.txt

EXPOSE 9000

ENV PYTHONPATH=/frontend/package
WORKDIR /frontend/data/
CMD python3 /frontend/frontend.py frontend.ini

