FROM python:3.11-slim
ARG DATA_DIRECTORY=demo-en_US
ARG EXTRA_APT_INSTALL_PKGS=""

RUN apt update
RUN apt upgrade -y
RUN apt install -y git gcc libasound2 libasound2-plugins libasound2-dev libportaudio2 portaudio19-dev espeak-ng-espeak espeak-ng-data $EXTRA_APT_INSTALL_PKGS

WORKDIR /kalliope

COPY ./requirements.txt  ./
COPY ./$DATA_DIRECTORY/  ./data/

RUN pip install --no-cache-dir -r requirements.txt -r data/requirements.txt

EXPOSE 5000

WORKDIR /kalliope/data/
CMD if [ -x ./run.sh ] ; then ./run.sh ; else kalliope start ; fi

