FROM python:3.11-slim
ARG DATA_DIRECTORY="demo-en_US"
ARG EXTRA_APT_INSTALL_PKGS=""

RUN apt update
RUN apt upgrade -y
RUN apt install -y $EXTRA_APT_INSTALL_PKGS

WORKDIR /brain

COPY ./requirements.txt  ./
COPY ./brain.py          ./
COPY ./package/          ./package/
COPY ./$DATA_DIRECTORY/  ./data/

RUN pip install --no-cache-dir -r requirements.txt -r data/requirements.txt

ENV PYTHONPATH=/brain/package
WORKDIR /brain/data
CMD python3 /brain/brain.py brain.ini

