default_trigger: "porcupine"
triggers:
  - precise:
      pb_file: "resources/data/precise/computer-en.pb"
      sensitivity: 0.5


default_speech_to_text: "vosk"
speech_to_text:
  - vosk:
      model_path: "resources/data/vosk/vosk-model-small-de-0.15"
      sample_frequency: 16000


default_text_to_speech: "pico2wave"
cache_path: "/tmp"
text_to_speech:
  - pico2wave:
      language: "de-DE"
      cache: True


default_player: "pyalsaaudio"
players:
  - pyalsaaudio:
     device: "default"
     convert_to_wav: True


hooks:
  on_start: "on-start"
  on_waiting_for_trigger:
  on_triggered: "on-triggered"
  on_start_listening: "on-start-listening"
  on_stop_listening:
  on_order_found:
  on_order_not_found: "on-order-not-found"
  on_processed_synapses: "on-processed"
  on_deaf:
  on_undeaf:
  on_start_speaking:
  on_stop_speaking:
  on_stt_error: "on-stt-error"


rest_api:
  active: True
  port: 5000
  password_protected: False
  login: admin
  password: secret
  allowed_cors_origin: "*"


resource_directory:
  signal:  "resources/signal"
  trigger: "resources/trigger"
  stt:     "resources/stt"
  tts:     "resources/tts"
  neuron:  "resources/neurons"


var_files:
  - variables/numbers.yml


options:
  recognizer_recording_timeout: 7.5
  recognizer_recording_timeout_with_silence: 1.5


send_anonymous_usage_stats: False

