FROM python:3.11-slim
ARG DATA_DIRECTORY="demo-en_US"
ARG EXTRA_APT_INSTALL_PKGS=""

RUN apt update
RUN apt upgrade -y
RUN apt install -y $EXTRA_APT_INSTALL_PKGS

WORKDIR /dashboard

COPY ./requirements.txt  ./
COPY ./dashboard.py      ./
COPY ./package/          ./package/
COPY ./resources/        ./resources/
COPY ./$DATA_DIRECTORY/  ./data/
RUN ln -s ../resources   ./data/resources

RUN pip install --no-cache-dir -r requirements.txt -r data/requirements.txt

EXPOSE 2001

ENV PYTHONPATH=/dashboard/package
WORKDIR /dashboard/data/
CMD python3 /dashboard/dashboard.py dashboard.ini

